export const ECOSYSTEM_CONTENT = {
    headline: {
        category: "Ecosystem",
        title: "Echo Everywhere",
        description: "We collaborate with leading platforms and infrastructure providers across DeFi to enable autonomous trading, execution, and data intelligence.",
    },
    cards: [
        {
            category: "CEXs",
            name: "Binance",
            description: "Binance is a global cryptocurrency exchange providing deep liquidity and trading infrastructure across multiple markets.",
            image: "/images/ecosystem/binance-b.png",
            isPng: true,
        },
        {
            category: "CEXs",
            name: "Coinbase",
            description: "Coinbase is a trusted digital asset platform offering secure access to crypto markets and on-chain services.",
            image: "/images/ecosystem/coinbase-c.avif",
            isPng: false,
        },
        {
            category: "Money Markets",
            name: "Morpho",
            description: "A permissionless, non-custodial protocol enabling efficient capital deployment and lending across DeFi.",
            image: "/images/ecosystem/morpho-m.avif",
            isPng: false,
        },
        {
            category: "Money Markets",
            name: "Euler",
            description: "Euler is a modular lending platform supporting advanced risk management and capital efficiency.",
            image: "/images/ecosystem/euler-e.avif",
            isPng: false,
        },
        {
            category: "DEXs",
            name: "Curve",
            description: "An on-chain liquidity protocol optimized for efficient swaps and deep liquidity environments.",
            image: "/images/ecosystem/curve-c.avif",
            isPng: false,
        },
        {
            category: "Yield",
            name: "Pendle",
            description: "Pendle enables tokenized yield strategies, supporting fixed, variable, and leveraged yield positions.",
            image: "/images/ecosystem/pendle-p.avif",
            isPng: false,
        },
        {
            category: "Bridge Oracle",
            name: "Chainlink",
            description: "Chainlink provides decentralized oracle infrastructure delivering reliable data feeds for on-chain execution.",
            image: null,
            icon: "chainlink",
            isPng: false,
        },
        {
            category: "Bridge",
            name: "LayerZero",
            description: "LayerZero enables secure omnichain messaging and cross-chain interoperability across ecosystems.",
            image: null,
            icon: "layerzero",
            isPng: false,
        },
    ],
    stats: [
        {
            value: "+30",
            label: "Integrated Protocols",
            icons: ["curve", "morpho", "euler"],
            extra: "+27",
        },
        {
            value: "4",
            label: "Supported Networks",
            icons: ["eth", "arbitrum", "base", "blast"],
            extra: null,
        },
        {
            value: "+80",
            label: "Execution Opportunities",
            badges: ["Strategies", "Vaults"],
            extra: "+3",
        },
    ],
};
