export const FAQ_CONTENT = {
    headline: {
        title: "Frequently asked questions",
        description: "Find the answers you need to confidently navigate and succeed with Usual.",
    },
    questions: [
        {
            question: "What is Usual?",
            answer: "Usual is a decentralized protocol, embracing the shape of a decentralized banking system. It issues a fiat-backed stablecoin, collateralized by Real-World Assets (RWAs), combining the security of real assets with the composability and liquidity of DeFi. More than just a stablecoin issuer, Usual puts ownership and governance back into users' hands through the $USUAL token."
        },
        {
            question: "Why choose Usual?",
            answer: "Usual offers a unique blend of security, transparency, and user-centric governance that sets it apart from traditional stablecoin issuers."
        },
        {
            question: "What makes Usual different?",
            answer: "Unlike centralized entities, Usual ensures that value generated by the protocol is redistributed to the community, fostering a truly equitable financial ecosystem."
        },
        {
            question: "What is USD0?",
            answer: "USD0 is the first liquid deposit token (LDT) providing access to Real-World Asset (RWA) yields. It is fully backed 1:1 by very short-term real-world assets, ensuring stability and security."
        },
        {
            question: "What is bUSD0?",
            answer: "bUSD0 represents a boosted version of USD0, allowing users to earn enhanced rewards and participate more actively in the protocol's ecosystem."
        },
        {
            question: "What is USUAL?",
            answer: "$USUAL is the governance and ownership token of the protocol. It allows holders to influence key decisions and share in the protocol's success."
        },
        {
            question: "Why is USUAL more than just a governance token?",
            answer: "USUAL represents real ownership in the protocol's infrastructure and treasury, aligning the interests of the protocol with those of its users."
        },
    ],
    cta: {
        text: "See full FAQ",
        href: "/faq",
    }
};
